# Configuración global
TOKEN=tu_token_aqui
TARGET=nyquist.ddns.net

# Notificaciones (Opcional)
# TG_BOT_TOKEN=
# TG_CHAT_ID=

[midominio.com]
ZONE=tu_zone_id_aqui

# formato: subdominio [PROXY/NO_PROXY]
@               PROXY
www             PROXY
vpn             NO_PROXY
